name: publish to galaxy

on:
  push:
    tags:
      - '*'

jobs:

  release:

    name: Release to galaxy

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Get the version name from the tags
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: publish to ansible galaxy
        uses: arillso/action.ansible.collection@master
        with:
          api_key: ${{ secrets.galaxy_api_key }}
          galaxy_version: '${{ env.RELEASE_VERSION }}'
