name: flake8

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Boot the docker containers with latest guacamole
      working-directory: ./devel-utils
      run: docker-compose up -d

    - name: Install latest ansible and make the collection available
      run: |
        mkdir -p ~/.ansible/collections/ansible_collections/scicore/
        ln -s ${GITHUB_WORKSPACE} ~/.ansible/collections/ansible_collections/scicore/guacamole
        pip install ansible

    - name: Execute the CI playbook
      working-directory: ./devel-utils
      run: ansible-playbook test-collection.yml


  release:
    name: Release to galaxy
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Get the version name from the tags
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: publish to ansible galaxy
        uses: arillso/action.ansible.collection@master
        with:
          api_key: ${{ secrets.galaxy_api_key }}
          galaxy_version: '${{ env.RELEASE_VERSION }}'
